### ISSUE TITLE
FR: Callback when memory is paged in

### ISSUE THREAD

**Issue by ghost** [bnoordhuis/node-mmap#5]
I don't know how hard would it be (or if ever possible), but would it be possible to add some function with callback which is called only when the memory is in fact paged in? Otherwise this stops the whole node process.

It is complicated by the fact the part of it can be paged in and part of it not and the whole part could not be there at once, ever.

Maybe something like:

mmapEnsure(file, offset, size, buffer /\* from previous mmap call */, wanted, function (err, before, after) {
  // now there is interval before...after paged in, before <= wanted <= after
});

(maybe not all args needed since buffer should know the file, offset and size)

**Comment by bnoordhuis** [comment]
> I don't know how hard would it be (or if ever possible), but would it be possible to add some function with callback which is called only when the memory is in fact paged in? Otherwise this stops the whole node process.

It's not really possible. There's a `mincore()` syscall that returns a snapshot of the page state at the time of the syscall. The problem is that the snapshot might very well be stale by the time the syscall returns unless you `mlock()` the memory - but then you know the memory is pinned so you wouldn't call `mincore()` in the first place.

On a side note, node-mmap was something of a mistake. It doesn't belong in an asynchronous environment and you probably shouldn't use it. I might scrap it entirely someday.

**Comment by ghost** [comment]
Not really. It is true that from the first and maybe the second sight as well  it is contrary to the single thread, non-blocking world, but then node is deprived of things like "best cache is the filesystem cache" and other nice tricks. It is good to have this, though one should be careful to use it.

In the meanwhile I found a workaround - inspired by 0mq which have dedicated thread to read and write - to spawn dedicated thread (process would be overkill) that would just read every n-th byte of the interval I want to have paged in (I must not choose too big one or it will backfire), and let me know through a socket or pipe - I can wait for it in node process non-blockingly.
